name: The SILShack class blog - Fall 2013
pygments: true
markdown: redcarpet

baseurl: /fall2013
url: 

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Elliott Hauser
  
authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Coursefork.org.  
  mbaxter:
      name: Michelle Baxter
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  abrown:
      name: Ashley Brown
      prof: false
      gravatar:
      website: 
      github: ashmbrown
      twitter: 
      about: I am a dual Master's student studying Library Science and Public Administration.  
  sburnham:
      name: Sarah Breen
      prof: false
      gravatar:
      website: 
      github: sbbreen
      twitter:
      about: Sarah is a first year MSIS student. Originally from Ohio, she has spent the last five years in Asia working in archives and as a project manager for several small organizations. Reach her on email at sburnham5@gmail.com. 
  ecarter:
      name: Erin Carter
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  odorsey:
      name: Olivia Dorsey
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  jgeer:
      name: James Geer
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  mgillen:
      name: Mary Gillen
      prof: false
      gravatar:
      website: 
      github: gillenme
      twitter:
      about:  Mary is a second year MSIS student focusing on information retrieval. Her interests include big data, data analytics and marketing.
  lgrindheim:
      name: Landon Grindheim
      prof: false
      gravatar:
      website: 
      github: landongrindheim
      twitter: landongrindheim
      about: Landon is an MSIS student at UNC Chapel Hill. He grew up in North Dakota, but has lived in Idaho, Montana and North Carolina as well as in the Middle East. His brain operates primarily in the humanities.
  aharding:
      name: Alexander Harold
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  lho:
      name: Leslie Ho
      prof: false
      gravatar:
      website: 
      github: leslieho
      twitter:
      about: Leslie is a BSIS and Anthropology double major.  She really likes puppies.
  eholmes:
      name: Erin Holmes
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  ckenrick:
      name: Christopher Kenrick
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  smantooth:
      name: Stacey Mantooth
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  gmclendon:
      name: Grant McLendon
      prof: false
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://gerbal.org
      github: gerbal
      twitter: gerbal100
      about:  Grant's a first year MSIS student.  
  vneisler:
      name: Virginia Neisler
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  dpcolar:
      name: David Pcolar
      prof: false
      gravatar:
      website: http://library.unc.edu
      github: pcolar
      twitter: pcolar
      about:  Dave is an IT professional with the University Library. My focus is infrastructure related project management and research on scalable storage environments. 
  epeele:
      name: Elizabeth Peele
      prof: false
      gravatar:
      website: 
      github: eipeele
      twitter: eipeele
      about:  Elizabeth Peele is a first year MSIS at the University of North Carolina Chapel Hill.  
  jpowell:
      name: Jaleesa Powell
      prof: false
      gravatar: 189c604692e488809bcf2770b70cc491
      website: http://jaleesapowell.net
      github: dieschwarzekobra
      twitter: JaleesaPowell
      about: Jaleesa is a second-year MSIS student at the University of North Carolina at Chapel Hill. Jaleesa is a Web Intern at the UNC General Alumni Association and the Digitization Intern at Campbell University.
  jpulliza:
      name: Jonathan Pulliza
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  kshaffer:
      name: Kyle Shaffer
      prof: false
      gravatar:
      website: 
      github: kylerthecreator
      twitter:
      about: First year MSIS student, novice Githubber, avid coffee drinker.  
  atickner:
      name: Amanda Tickner
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
  danielle:
      name: Danielle Wingler
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  I am a BSIS student. I am looking forward to learning more about programming. I am still exploring career paths within the information science field.
  zyu:
      name: Zekun Yu
      prof: false
      gravatar:
      website: 
      github:
      twitter:
      about:  
